services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=sqs
      - AWS_REGION=us-east-1

  mysql:
    image: mysql:8.0
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: calendar
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_USER=user
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=calendar
    depends_on:
      - mysql
      - localstack
    ports:
      - "8080:8080"
    command: ["/root/api"]  # Path to your binary

  consumer:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_USER=user
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=calendar
    depends_on:
      - mysql
      - localstack
    command: ["/root/consumer"]  # Path to your binary

  cron:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - DATABASE_HOST=mysql
      - DATABASE_USER=user
      - DATABASE_PASSWORD=password
      - DATABASE_NAME=calendar
    depends_on:
      - mysql
      - localstack
    command: ["/root/cron"]  # Path to your binary

volumes:
  mysql-data:
